local utils = require('grug-far/utils')

describe("strEllideAfter", function()
  it('returns empty string if n = 0', function()
    assert.combinators.match('', utils.strEllideAfter("hello world", 0))
  end)
  it('returns string if strlen < n', function()
    assert.combinators.match('hello world', utils.strEllideAfter("hello world", 20))
  end)
  it('returns ellided strign if strlen > n', function()
    assert.combinators.match('hello...', utils.strEllideAfter("hello world", 5))
  end)
  it('adds prefix if proficed', function()
    assert.combinators.match('say hello...', utils.strEllideAfter("hello world", 5, 'say '))
  end)
end)
