name: lint

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint with selene
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run selene
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --display-style=quiet .

  style-lint:
    name: Stylua check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Lint with stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  typecheck-emmylua:
    name: Typecheck sources
    strategy:
      matrix:
        os: [ubuntu-latest]
        neovim_version: ["v0.11.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install emmylua_check from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: emmylua_check
          version: '^0.10.0'
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      - uses: actions/checkout@v4
      # TODO (sbadragan): need to fetch LLS_Addons -> luvit library as well
      - name: Run emmylua_check
        run: |
          export VIMRUNTIME=$( nvim -u NORC --headless -c 'echo $VIMRUNTIME' -c 'q' 2>&1)
          echo $VIMRUNTIME
          emmylua_check -c .emmyrc.json ./lua ./tests
