name: Bump version and release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: false
        DEFAULT_BUMP: patch

    - name: LuaRocks Upload 
      uses: nvim-neorocks/luarocks-tag-release@v7
      with:
        name: grug-far.nvim
        labels: neovim
        version: ${{ steps.bump_version.outputs.new_tag }}
      env:
        LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
